package com.example.wmc.database;

public class Review {
    private Long reviewNum;
    private byte[] reviewImage;
    private Long categoryNum;
    private Integer likeCount;
    private String reviewText;
    private Long keyword1;
    private Long keyword2;
    private Long keyword3;
    private Long keyword4;
    private Long keyword5;
    private Long keyword6;
    private Long keyword7;
    private Long keyword8;
    private Long keyword9;
    private Long keyword10;
    private Long keyword11;
    private Long keyword12;
    private Long keyword13;
    private Long keyword14;
    private Long keyword15;
    private Long keyword16;
    private Long keyword17;
    private Long keyword18;
    private Long keyword19;
    private Long keyword20;
    private Long keyword21;
    private Long keyword22;
    private Long keyword23;
    private Long keyword24;
    private Long keyword25;
    private Long keyword26;
    private Long keyword27;
    private Long keyword28;
    private Long keyword29;
    private Long keyword30;
    private Long keyword31;
    private Long keyword32;
    private Long keyword33;
    private Long keyword34;
    private Long keyword35;
    private Long keyword36;
    private Long memNum;
}
